### ISSUE TITLE
Can't export due to a few errors(enconding and long filename)

### ISSUE THREAD

**Issue by RealDrJester** [na-trium-144/vivaldi-notes-export#1]
Hello;
Thank you for the script. I have been looking for something like this for years. But there are a few issues. My notes file is around 14MB. 

I tried to export it, but the first issues I have bumped into is the script not identifying the enconding of the notes file. Which I think, in my very limited programming knowledge, I solved it by changing a line into this: 

`with open(notes_file, "r", encoding="utf-8", errors="replace") as f:`

But unfortunately, it is creating filenames too long to be saved. And I can't find out how to truncate it to something like 20 characters or 30. 

Can you update the script with this? 

Thank you again for this. I will keep trying, but I suspect I won't get too far.

**Comment by na-trium-144** [comment]
Thanks for reporting the issue.
The encoding error should be fixed and filenames are now limited to the first 30 characters with https://github.com/na-trium-144/vivaldi-notes-export/commit/ed741a5619d118b9c022a5d1c77133498e21f584 .

**Comment by RealDrJester** [comment]
Thank you so very much! This got a lot further! 

Now there is another issue that throws this error:


` "OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'F:\\Vivaldi_Notes\\Notes\\"Something else!"'"`


And I also noticed that one has to add this at line 34, as the filepath also throws an error over the character. 

`with open(filepath, "w+", encoding="utf-8", errors="replace") as f:`

**Comment by na-trium-144** [comment]
I see.
I think those are fixed with https://github.com/na-trium-144/vivaldi-notes-export/commit/7f2f463e4fc53c294d13c20304979e429d64dc35.

**Comment by RealDrJester** [comment]
Thank you!!!!! 

This got even further. Found a fix for one of the errors, as it seems  I had some sort of "tab" on the text by adding on line 25 and 39 this modification `r'\	/:*?"<>|'`

And it seems it doesn't like when the folder(in vivaldi folder structure) ends with a space. Nor with periods(and I assume with any other character) 
For instance:

FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Vivaldi_Notes\\Foo\\Foo2\\Foo3\\Foo4\\Foo5 - Foo6 and  \\foo7.txt'


EDIT: had to use code formating below because github was losing some of the characters. 
`adding "_" at the of the "Foo5 - Foo6 and  " to become "Foo5 - Foo6 and_" fixes the issue inside vivaldi.`

**Comment by na-trium-144** [comment]
Hmm, since it seems there are so many restriction on filename than I expected, maybe we should use external library.
I found [pathvalidate](https://github.com/thombashi/pathvalidate) can sanitize the filename for any platform, so I changed the code to use that library.
I think it should work fine (with `pip install pathvalidate`) but feel free to ask again if you still have any problem.

**Comment by RealDrJester** [comment]
This is one ran flawlessly and converted everything. No problems whatsoever! 

THANK YOU SOOOO MUCH!!
